env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
script: bundle exec rspec
matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: 2.2
      gemfile: Gemfile
    - rvm: 2.3.0
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: jruby-head
      gemfile: Gemfile
    - rvm: rbx-2
      gemfile: Gemfile
    - rvm: ruby-head
      gemfile: Gemfile
  fast_finish: true
sudo: false
